apiVersion: apps/v1
kind: Deployment
metadata:
  name: dc-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dc-ui
  template:
    metadata:
      labels:
        app: dc-ui
    spec:
      containers:
        - name: dc-ui
          image: inseefr/coleman-my-surveys:0.2.0-rc
